spring.application.name=cart-service
server.port=8083

spring.datasource.url=jdbc:mariadb://cart-db:3306/cartdb
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

book.service.url=http://book-service:8082