apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-db
  template:
    metadata:
      labels:
        app: book-db
    spec:
      containers:
        - name: book-db
          image: mariadb:11
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "1234"
            - name: MARIADB_DATABASE
              value: "bookdb"
---
apiVersion: v1
kind: Service
metadata:
  name: book-db
spec:
  selector:
    app: book-db
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  type: ClusterIP
