spring.application.name=user-service
server.port=8081

spring.datasource.url=jdbc:mariadb://user-db:3306/userdb
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

app.jwtSecret=Ym9va3N0b3JlU2VjcmV0S2V5R2VuZXJhdGVkQnlDb3BpbG90Rm9yVGVzdGluZ1B1cnBvc2VzMTIzNDU2Nzg5
app.jwtExpiration=86400000