spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=book-service
spring.cloud.gateway.server.webmvc.routes[0].uri=${BOOK_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/books/**

spring.cloud.gateway.server.webmvc.routes[1].id=cart-service
spring.cloud.gateway.server.webmvc.routes[1].uri=${CART_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/cart/**

spring.cloud.gateway.server.webmvc.routes[2].id=order-service
spring.cloud.gateway.server.webmvc.routes[2].uri=${ORDER_SERVICE_URL:http://localhost:8084}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/orders/**

spring.cloud.gateway.server.webmvc.routes[3].id=user-service
spring.cloud.gateway.server.webmvc.routes[3].uri=${USER_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/users/**

spring.cloud.gateway.server.webmvc.routes[4].id=payment-service
spring.cloud.gateway.server.webmvc.routes[4].uri=${PAYMENT_SERVICE_URL:http://localhost:8085}
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/payments/**